name: ci

on:
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/raddy-blog:latest
          

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:

#     - name: Checkout
#     - uses: actions/checkout@v4

    
#     - name: docker login
#       uses: ocker/login-action@v3
#       with:
#        DOCKER_USER: ${{secrets.DOCKER_USER}}
#        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#       # run:
#       #  docker login -u $DOCKER_USER -P $DOCKER_PASSWORD
    
#     - name: Build The Docker image
#       run:
#        docker build . --file Dockerfile --tag amdevops09/raddy-blog:$(date +%s)
    
#     - name: Docker PUSH
#       run:
#        docker push ${{secrets.DOCKER_USER}}/raddy-blog
